### ISSUE TITLE
RGE seems like it doesn’t come with SSE Engine Fixes fully installed

### ISSUE THREAD

**Issue by Kyle-sys** [jdsmith2816/rge#10]
**Describe the bug**
According to the manifest, part 2 of SSE Engine Fixes isn’t there. So only part 1 is, in thus making Engine Fixes not work/not fully installed. The file d3dx9_42.dll (needed for part 2 of Engine fixes) isn’t in the game folder files.

**To Reproduce**
1. Download/install latest RGE via Wabbjack (idk if github version has the same issue) and navigate to the game folder files and look for above file, it should be missing.
2. Attempt to f5 in game, saves do not get turned into manual saves. They are still quicksaves.

**Expected behavior**
For both parts of Engine Fixes to be installed.

**Modlist version**
RGE 2.0.13
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
https://i.imgur.com/0aIWS67.png

It appears to be there for me?

**Comment by Kyle-sys** [comment]
I’ll close this then. On two different computer it wasn’t being put there ugh. Idk what is going on.

**Comment by jdsmith2816** [comment]
Going to reopen until I do this next update so I can tripple check that everything is correct.

**Comment by Kyle-sys** [comment]
Okay sounds awesome. Ty for looking Into it a bit more :) I ended up manually downloading part 2 and putting that file where my SkyrimSE.exe is at, and it seems to be doing good atm.

**Comment by jdsmith2816** [comment]
Fixed in 2.1.0;  long story short.. due to a WJ bug this was able to happen even though the file was still present on my end.  Thanks for the report!

**Comment by Kyle-sys** [comment]
Yup no problem. Glad it has been sorted out.
