### ISSUE TITLE
Engine Fixes Version 5 reported as incompatible.

### ISSUE THREAD

**Issue by lexcia98** [jdsmith2816/rge#12]
**Describe the bug**
Users reporting being unable to launch due to error they said is fixed by 
**To Reproduce**
Install list on fresh install of Skyrim, try to run list.

**Expected behavior**
Crash and error.

**Screenshots**
https://cdn.discordapp.com/attachments/681651975686979613/715352914247548958/Anmerkung_2020-05-28_015626.png

**Modlist version**
Latest as of  7:09 PM Central time on 5/27/2020

**Comment by mael5trum** [comment]
I had a similar issue and fixed it by manually reinstalling '(Part 2) Engine Fixes - skse64 Preloader and TBB Lib'

**Comment by jdsmith2816** [comment]
Fixed in 2.1.0
