### ISSUE TITLE
Rayya's Purple shiny hair

### ISSUE THREAD

**Issue by CentralSmith** [jdsmith2816/rge#14]
**Describe the bug**
Rayya, the Falkreath Housecarl, has what appears to be untextured, shiny purple hair.

**To Reproduce**
Proceed through Falkreath Thaneship, recruit Rayya

**Expected behavior**
Textured hair

**Screenshots**
https://i.gyazo.com/7effef846dcbcbe128fe1dcbf990b847.jpg
https://i.gyazo.com/da2ca77ae221fa6544a6d93a03da15de.jpg

**Modlist version**
2.0.14

**Did you add any additional mods?**
Yes (Leveler's Tower), however, it does not affect this function.

**Comment by jdsmith2816** [comment]
Fixed in 2.1.0
