### ISSUE TITLE
Unlocked Merchant Chest in Windhelm, Owner is Gindas Ildram, Chest id is (Base Form ID: 9F025659, Ref Form ID: 9F02565B)

### ISSUE THREAD

**Issue by igigo003** [jdsmith2816/rge#18]
**Describe the bug**

**To Reproduce**

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**

**Did you add any additional mods?**

**Comment by jdsmith2816** [comment]
Fixed in 2.1.0
