### ISSUE TITLE
Fur Rags armor value

### ISSUE THREAD

**Issue by CentralSmith** [jdsmith2816/rge#20]
**Describe the bug**
The light armor, Fur Rags (740012CD) and it's associated counterpart Dark Fur Rags (7400436F) have an armor value of 45, compared to Steel Armor, heavy, rating in at 33, with a much higher value.

**To Reproduce**
Observe with your eyes.

**Expected behavior**
Rags to not be structurally more sound than steel.

**Screenshots**
![image](https://user-images.githubusercontent.com/1962028/83320758-08db7d00-a210-11ea-8cda-a15fa3d94252.png)
![image](https://user-images.githubusercontent.com/1962028/83320761-0e38c780-a210-11ea-9239-d07f3f956e00.png)

**Modlist version**
2.0.14

**Did you add any additional mods?**
Yes, none affect this situation.

**Comment by jdsmith2816** [comment]
Cannot reproduce in 2.1.0; the records have 78 as base for all steel armor and 42 for fur rags.
