### ISSUE TITLE
Training Dummy inside wall

### ISSUE THREAD

**Issue by Kyle-sys** [jdsmith2816/rge#21]
**Describe the bug**
There is a training dummy stuck inside of a wall of sorts in Windhelm.

**To Reproduce**

1. Go to Windhelm, and go to where the Aretino Residence building is at, the dummy is near there.

**Expected behavior**
I believe that the Training Dummy shouldn't be in the wall.

**Screenshots**
![Skyrim Special Edition 5_30_2020 9_19_59 AM](https://user-images.githubusercontent.com/52866222/83329435-7d85da00-a257-11ea-8e5a-2bce50188b37.png)

**Modlist version**
RGE 2.0.14
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 2.1.0
