### ISSUE TITLE
Water texture outside Solitude dock area

### ISSUE THREAD

**Issue by CentralSmith** [jdsmith2816/rge#22]
**Describe the bug**
The texture of water outside of the solitude dock has a jarring edge that is very noticeable even from a distance.

**To Reproduce**
Head just up the waterway from the solitude lumber mill.

**Expected behavior**
Smooth water texture

**Screenshots**
![image](https://user-images.githubusercontent.com/1962028/83330622-e704e900-a255-11ea-9236-cd3cf1ed30e1.png)

**Modlist version**
2.0.14

**Did you add any additional mods?**
Yes, none affect this area.

**Comment by jdsmith2816** [comment]
Fixed in 2.1.0
