### ISSUE TITLE
Game seems to hard freeze when looking at a specific area in Windhelm

### ISSUE THREAD

**Issue by Kyle-sys** [jdsmith2816/rge#23]
**Describe the bug**
Edit: So it is that bald guy from issue 17 If his ai process is turned off the game doesn't freeze, as soon as his ai process is re-enabled the game does freeze interesting. Screenshot and vid are below

**To Reproduce**

1. Go to Windhelm and attempt to go to Windhelm Market.

**Expected behavior**
The game shouldn't freeze when I go there.

**Screenshots**
I have a YouTube vid of it happening, hopefully it is okay:
https://youtu.be/Hq-uUPdgW0M

![Skyrim Special Edition 5_30_2020 3_04_27 PM](https://user-images.githubusercontent.com/52866222/83337151-1849dd00-a287-11ea-90f2-01d0e57f5d98.png)

**Modlist version**
RGE 2.0.14
**Did you add any additional mods?**
No

**Comment by Kyle-sys** [comment]
I tried uploading a video, but it seems like I can't, if you need the video, just let me know and I can upload it on discord or something.

**Comment by Kyle-sys** [comment]
Oof I didn’t double check the issues listed here as this seems like it could be a dublicate of issue 17. Idk if you want me to close it or not.

**Comment by jdsmith2816** [comment]
Fixed in 2.1.0
