### ISSUE TITLE
LC_Build Your Noble House 'Activate Build Plans' function not working

### ISSUE THREAD

**Issue by CentralSmith** [jdsmith2816/rge#24]
**Describe the bug**
After building a building plan for the Fellburg location at the carpenter bench, the 'build plan' object beside it refuses to activate, preventing any construction and making the entire mod inoperable.

**To Reproduce**

1. Go to Fellburg
2. Build a building plan - any will do.
3. Attempt to activate the 'Activate Build Plans' function of the planning table

**Expected behavior**
A menu option to construct building plans added to the inventory via the carpenter bench

**Screenshots**
![image](https://user-images.githubusercontent.com/1962028/83334889-2986ef80-a26f-11ea-9c8d-d7d31f771bd5.png)

**Modlist version**
2.0.14

**Did you add any additional mods?**
Yes, none affect this issue.

**Comment by GoAhead-at** [comment]
same issue as described above :-/

**Comment by alphabeno** [comment]
Anyone fixed it yet?

**Comment by lexcia98** [comment]
https://github.com/lexcia98/rge/blob/master/README.md
Support moved to new page months ago. Issue was fixed in an update a while ago. Involved reassigning dialogue topics from that mod in the ECTV merge. Please take issues to the current github.

**Comment by jdsmith2816** [comment]
@lexcia98 Shall I archive this repository to remove confusion?

**Comment by lexcia98** [comment]
> 

Good idea.
