### ISSUE TITLE
Sorex Vinius has purple eyes

### ISSUE THREAD

**Issue by Kyle-sys** [jdsmith2816/rge#25]
**Describe the bug**
Title should be enough.

**To Reproduce**

1. Go to Solitude and look for him at the execution event.

**Expected behavior**
For his eyes to be normal.

**Screenshots**
![Skyrim Special Edition 5_30_2020 3_37_39 PM](https://user-images.githubusercontent.com/52866222/83337769-15052000-a28c-11ea-9ed4-8246021d7f02.png)

**Modlist version**
RGE 2.0.14
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 2.1.0
