### ISSUE TITLE
The person named Vigilant Norik has the black face bug

### ISSUE THREAD

**Issue by Kyle-sys** [jdsmith2816/rge#26]
**Describe the bug**
Hopefully title is good enough.

**Expected behavior**
For the persons face to be normal.

**Screenshots**
![Skyrim Special Edition 5_30_2020 4_43_02 PM](https://user-images.githubusercontent.com/52866222/83338714-0707cd00-a295-11ea-81f4-0f14c45b6cb0.png)
![Skyrim Special Edition 5_30_2020 4_43_10 PM](https://user-images.githubusercontent.com/52866222/83338716-0838fa00-a295-11ea-8741-3f02e561cb1c.png)

**Modlist version**
RGE 2.0.14.
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 2.1.0
