### ISSUE TITLE
Most of Building has messed up looking textures

### ISSUE THREAD

**Issue by Kyle-sys** [jdsmith2816/rge#27]
**Describe the bug**
Hopefully title is enough.

**Expected behavior**
Building should look normal.
**Screenshots**
![Skyrim Special Edition 5_30_2020 5_04_21 PM](https://user-images.githubusercontent.com/52866222/83339062-fc9b0280-a297-11ea-86cb-a6a1c794dcb4.png)
![Skyrim Special Edition 5_30_2020 5_04_28 PM](https://user-images.githubusercontent.com/52866222/83339065-fe64c600-a297-11ea-85c3-b356d471ee86.png)
![Skyrim Special Edition 5_30_2020 5_04_36 PM](https://user-images.githubusercontent.com/52866222/83339067-00c72000-a298-11ea-87e7-85aecafd686b.png)

**Modlist version**
RGE 2.0.14
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 2.1.0
