### ISSUE TITLE
Armor is at 0 for the Penitus Oculatus Helmet and Boots

### ISSUE THREAD

**Issue by Kyle-sys** [jdsmith2816/rge#28]
**Describe the bug**
Hopefully title is enough.

**To Reproduce**
Look at the pieces of gear in inventory and observe the 0 armor rating. 

**Expected behavior**
For them not to have 0 armor.

**Screenshots**
![Skyrim Special Edition 5_30_2020 5_35_50 PM](https://user-images.githubusercontent.com/52866222/83339737-abdad800-a29e-11ea-9256-4a4bd2ecbc91.png)
![Skyrim Special Edition 5_30_2020 5_52_15 PM](https://user-images.githubusercontent.com/52866222/83339741-b1382280-a29e-11ea-801c-10fed8a3d01b.png)
![Skyrim Special Edition 5_30_2020 5_35_57 PM](https://user-images.githubusercontent.com/52866222/83339742-b2694f80-a29e-11ea-8eb1-fe0de23380ff.png)
![Skyrim Special Edition 5_30_2020 5_52_08 PM](https://user-images.githubusercontent.com/52866222/83339745-b39a7c80-a29e-11ea-919a-7ddf225d093e.png)

**Modlist version**
RGE 2.0.14
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in v2.1.0
