### ISSUE TITLE
Armored Skeleton doesn't seem to attack, but the creature that spawns from it does.

### ISSUE THREAD

**Issue by Kyle-sys** [jdsmith2816/rge#29]
**Describe the bug**
I am at the Bloodworm place doing a quest, and the armored skeleton itself doesn't attack, but it seems like whatever creature spawns from its death does.

**To Reproduce**

1. Go to the Bloodworm content, and make your way through it until you come across the above mentioned creature, It shouldn't attack you for some reason.

**Expected behavior**
I think it should attack idk for sure though.

**Screenshots**
here is the video: https://youtu.be/ReicdQ01h_o

![Skyrim Special Edition 5_30_2020 6_15_01 PM](https://user-images.githubusercontent.com/52866222/83340130-98317080-a2a2-11ea-935f-3f6a5c1ce731.png)

**Modlist version**
RGE 2.0.14
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Hmmm I was unable to reproduce this.  Please try again once 2.1.0 releases and reopen if the behavior persists?
