### ISSUE TITLE
Dwemer Spectres EBT No Blood Patch and Other Fixes-26954-1-3-1589822027.7z   --Need 1.2 version to finish instal of this 80 gb download modpack :(. please update you modpack to verify version 1.3 as the new mod as there is no longer any version 1.2 now. or i have waisted over 80 gbs download cap.

### ISSUE THREAD

**Issue by werzel2020** [jdsmith2816/rge#3]
Dwemer Spectres EBT No Blood Patch and Other Fixes-26954-1-3-1589822027.7z   --Need 1.2 version to finish instal of this 80 gb download modpack :(. please update you modpack to verify version 1.3 as the new mod as there is no longer any version 1.2 now. or i have waisted over 80 gbs download cap.

**Comment by werzel2020** [comment]
The file needs to update in your mod list instal, can you please update your list to Dwemer Spectres EBT No Blood Patch and Other Fixes-26954-1-3-1589822027.7z version.  I cannot find version 1.2 anywhere, i have even tried modifying your modpack wabbajack file to 1.3 as 1.3, but even after changing the file name to  1.2, is still does not see it as 1.2.

**Comment by werzel2020** [comment]
Can i get some help with this please, as i have spent hours downloading this for it to all fail due to one tiny file update ?. Thanks in advance as i do appreciate any help given .

**Comment by jdsmith2816** [comment]
Use the updated installer.
