### ISSUE TITLE
More armor pieces that has a 0 armor rating on it

### ISSUE THREAD

**Issue by Kyle-sys** [jdsmith2816/rge#30]
**Describe the bug**
Hopefully title is enough.

**Expected behavior**
I think they should have some armor number rating idk for sure though.

**Screenshots**
![Skyrim Special Edition 5_31_2020 8_54_44 AM](https://user-images.githubusercontent.com/52866222/83352928-0286f700-a31d-11ea-821d-eef0415e3e3c.png)
![Skyrim Special Edition 5_31_2020 8_55_02 AM](https://user-images.githubusercontent.com/52866222/83352941-0dda2280-a31d-11ea-9b95-397c422cbc8c.png)
![Skyrim Special Edition 5_31_2020 8_55_09 AM](https://user-images.githubusercontent.com/52866222/83352916-ea16dc80-a31c-11ea-9044-33d47467dfe3.png)
![Skyrim Special Edition 5_31_2020 8_55_18 AM](https://user-images.githubusercontent.com/52866222/83352921-f69b3500-a31c-11ea-8c29-d7255d760b57.png)

**Modlist version**
RGE 2.0.14
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Those are all clothing; they aren't supposed to have armor ratings.
