### ISSUE TITLE
Faendal Black Face Bug

### ISSUE THREAD

**Issue by tHiNgXX9** [jdsmith2816/rge#37]
**Describe the bug**
Faendal Black Face Bug 

**To Reproduce**
Go to Riverwood and checkout Faendal

2. Do '...'

**Expected behavior**
Regular Faendal Face

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**
Newest Version with the Smoking torches Fix
**Did you add any additional mods?**
None
![20200602111052_1](https://user-images.githubusercontent.com/62521502/83554726-11f37500-a4c2-11ea-8378-b6ac844ddca9.jpg)

**Comment by jdsmith2816** [comment]
Fixed in latest version.
