### ISSUE TITLE
Installation failed (Invalid hash)

### ISSUE THREAD

**Issue by realVato** [jdsmith2816/rge#38]
I get this error after finishing extracting all mods, deleting temps and then hashing:
'Encountered error, cant continue - Invalid hash for mods / DynDOLOD resources / scripts / SHESON_DynDOLOD_Alias.pex after patching'.

I tried playing the game and it works still with all the mods, but obviously without them being cleaned and optimized due to install only partially completed.

**Comment by jdsmith2816** [comment]
You need to use the latest installer.
