### ISSUE TITLE
Getting what seems like Vampire messages, when Im not a vampire.

### ISSUE THREAD

**Issue by Ozsavsta** [jdsmith2816/rge#4]
**Describe the bug**
Getting 'Your flesh begins to smoulder as the sunlight touches your skin'

**To Reproduce**
No Idea

![ScreenShot4](https://user-images.githubusercontent.com/65318640/82293523-0a2acf80-99f0-11ea-9828-c59669ee6b7d.png)
**Expected behavior**
Not to receive error.

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**

**Did you add any additional mods?**

**Comment by jdsmith2816** [comment]
This seems to just randomly happen when Curse of the Vampire mod is installed.  I think there's a buggy conditional.  You can safely ignore it though as unless you're a vampire it actually has no effect.

Leaving this open for now.

**Comment by Ozsavsta** [comment]
Sweet, thanks for that.
