### ISSUE TITLE
Cant mine

### ISSUE THREAD

**Issue by Ozsavsta** [jdsmith2816/rge#5]
**Describe the bug**
Unable to mine

**To Reproduce**
Im not sure

2. Do '...'

**Expected behavior**
Should be able to look at ore and mine.
![ScreenShot5](https://user-images.githubusercontent.com/65318640/82293700-4827f380-99f0-11ea-8a30-48fe9725fb66.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**

**Did you add any additional mods?**

**Comment by jdsmith2816** [comment]
Resolved in 2.1.1
