### ISSUE TITLE
CTD with 3 or more followers

### ISSUE THREAD

**Issue by thehackedone** [jdsmith2816/rge#6]
The bug is when I have 2 followers I don't crash, when I have 3 or more, I CTD often. Also merchants outside of buildings always crash my game as well, this may be related but I have not tested it. Having 3 or more followers in a shop causes a CTD when I dismiss any number of them I have no issues. This is on Relics of Hyrule GAT Edition.

**Describe the bug**

**To Reproduce**

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**

**Did you add any additional mods?**

**Comment by jdsmith2816** [comment]
Unable to reproduce on 2.1.0
