### ISSUE TITLE
Balimund Purple Face

### ISSUE THREAD

**Issue by tHiNgXX9** [jdsmith2816/rge#8]
**Describe the bug**

**To Reproduce**

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**

**Did you add any additional mods?**

**Comment by tHiNgXX9** [comment]
Half of Balimunds face is missing and is purple. 
Just walked into Riften after starting a new playthrough of RGEGAT and this was appearing.

I believe I'm on 2.0.10 of RGEGAT and plan on updating it to the latest release. 

![20200524105518_1](https://user-images.githubusercontent.com/62521502/82761212-d19f4300-9dad-11ea-8355-aa2e2ef4bcf8.jpg)
![20200524105513_1](https://user-images.githubusercontent.com/62521502/82761214-d663f700-9dad-11ea-9e74-0224122bde9d.jpg)

No additions mods added whatsoever.

**Comment by jdsmith2816** [comment]
Thanks.  I know what's causing this. It'll be fixed in the next RGE release.

**Comment by jdsmith2816** [comment]
Fixed in 2.1.1
