### ISSUE TITLE
Dyndolod SSE error

### ISSUE THREAD

**Issue by Pepin90** [jdsmith2816/rge#9]
**Describe the bug**
I can't rerun Dyndolod because the program stops showing the error photographed in the screenshot.

**To Reproduce**

1. Remove all the contents in Dyndolod output folder in MO2 left pane (Dyndolod.esp; Dyndolod.esm and the other files);
2. Deactivate occlusion.esp in MO2 right pane;
3. Run Dyndolod from MO2.

**Expected behavior**
The screeshot error will appear a few seconds after starting Dyndolod forcing the program to stop starting.

**Screenshots**
I uploaded it above.

**Modlist version**
Relics of Hyrule GAT edition

**Did you add any additional mods?**
No, I didn't. I have installed a fresh install of the modlist above with clean Skrim install.
![Dyndolod error](https://user-images.githubusercontent.com/65945826/82877800-f1b03d00-9f3a-11ea-99f0-b17b3fd068e2.jpg)

**Comment by jdsmith2816** [comment]
Fixed in 2.1.0
